export enum PlayerActionTypes {
    TWO_POINTS = "TWO_POINTS",
    THREE_POINTS = "THREE_POINTS",
    PASS = "PASS",
    FOUL = "FOUL",
    OFFENSIVE_REBOUND = "OFFENSIVE_REBOUND",
    DEFENSIVE_REBOUND = "DEFENSIVE_REBOUND",
}